# Generated by Django 5.1.1 on 2024-10-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('slug', models.SlugField(unique=True)),
                ('body', models.TextField()),
                ('img', models.ImageField(upload_to='posts')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
